version: '2.4'

networks:
  default:

services:
  bridge-http:
    image: tw-blockchain/reconciliation-bridge-http-mock 
    expose:
      - 12306
    volumes:
      - ./mock/bridge-http:/moco/config
    networks: 
      - default

  payment-mysql:
    image: mysql:latest
    expose:
      - 3306
    volumes:
      - ./mock/payment-mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=origin_data
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 30s
      timeout: 10s
      retries: 5
    networks: 
      - default

  loader-db:
    container_name: loader-db
    image: mysql:latest
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=loader
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - default

  loader:
    image: tw-blockchain/reconciliation-loader
    depends_on:
      loader-db:
        condition: service_healthy
      bridge-http:
        condition: service_started
      payment-mysql:
        condition: service_healthy
    expose:
      - 8081
    ports:
      - 8081:8081
    environment:
      - LOADER_DB_HOST=loader-db
      - LOADER_DB_PORT=3306
      - LOADER_DB_NAME=loader
      - DATASOURCE_DB_HOST=payment-mysql
      - DATASOURCE_DB_PORT=3306
      - DATASOURCE_DB_NAME=origin_data
      - MOCK_SERVER_HOST=bridge-http
      - MOCK_SERVER_PORT=12306
    networks: 
      - default

  # demo:
  #   image: tw-blockchain/reconciliation-demo
  #   restart: unless-stopped
  #   environment:
  #     - RUST_LOG=demo=debug,actix_web=info
  #     - HTTP_ADDRESS=0.0.0.0
  #     - HTTP_PORT=8080
  #     - HTTP_LOADER_URL=http://loader:8081
  #     - PLUGIN_DIR=plugin
  #   expose: 
  #     - 8080
  #   ports:
  #     - 8080:8080
  #   logging:
  #     driver: "json-file"
  #   depends_on:
  #     loader:
  #       condition: service_started
  #   networks:
  #     - default