server:
  port: 8081
  address: 0.0.0.0

spring:
  batch:
    job:
      enabled: false
    initialize-schema: always
  profiles: dev
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:mysql://localhost:3307/loader?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# for multiple data sources, different data source for different loader
loader:
  payment:
    datasource:
      url: jdbc:mysql://localhost:3306/origin_data?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=falseallowPublicKeyRetrieval=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  bridge:
    url: http://127.0.0.1:12306/bridge-records